version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - streamlit

  streamlit:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port 8501 --server.enableCORS false
